### ISSUE TITLE
Minimizing dependency requirements for LanguageFlow

### ISSUE THREAD

**Issue by BLKSerene** [undertheseanlp/languageflow#96]
* LanguageFlow version: 1.1.13a1
* Python version: 3.7.4
* Operating System: Windows 10 64-bit

`scikit-learn` is not used anywhere inside `LanguageFlow`, so it should be removed from the dependency requirements.

**Comment by rain1024** [comment]
I use scikit-learn here

https://github.com/undertheseanlp/languageflow/blob/2e26c62de4d70560ad67bf0b098d4e8519d4bccb/languageflow/model/sgd.py#L1

**Comment by BLKSerene** [comment]
I see, sorry for having missed that.
